### ISSUE TITLE
There was a problem in sending this request. Please try again 403.

### ISSUE THREAD

**Issue by vistula1337** [BuycraftPlugin/Tebex-FiveM#6]
Hi, it may be my fault but every time the server starts after a while I get a notification back from the script I included in the title. Is this a common error or is it my fault? Any advice on how to fix this?
Greetings
![image](https://user-images.githubusercontent.com/53919028/154672937-07ca2efd-456d-4482-82b9-e03101731550.png)

**Comment by entity** [comment]
Hi there,

Thank you for reaching out to us regarding this issue. Unfortunately, this issue happened some time ago, and it's not feasible for us to investigate it now, as we don't have enough information to replicate the issue.

If you encounter a similar issue again, please feel free to create a new GitHub ticket and provide us with as much detail as possible so we can investigate it.

Thank you for your understanding, and we apologise for any inconvenience this issue may have caused.

Best regards,
The Integrations Team.
