### ISSUE TITLE
will this work with Redm ??

### ISSUE THREAD

**Issue by James-the-Coding-Gamer** [BuycraftPlugin/Tebex-FiveM#7]
will this work with Redm ??

**Comment by entity** [comment]
Hi there,

Thank you for reaching out to us relating to our plugin.

Regarding your question about whether our product works with RedM, please note that this repository is specifically for FiveM and not for RedM. While there may be similarities between the two platforms, they are also different in many respects.

If you have any further questions or concerns, please don't hesitate to let us know. We'd be happy to help.

Best regards,
The Integrations Team.
